/* eslint-disable */
// Generated by Wrangler by running `wrangler types --env-file=.env.typegen --include-runtime=false --env-interface=WorkerBindings src/worker-configuration.d.ts` (hash: 3c9ab56e74d8cbe6ee5ee31dbedef5cd)
interface __BaseEnv_WorkerBindings {
	DB: D1Database;
	AI: Ai;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./index");
	}
	interface Env extends __BaseEnv_WorkerBindings {}
}
interface WorkerBindings extends __BaseEnv_WorkerBindings {}
