/* eslint-disable */
// Generated by Wrangler by running `wrangler types --env-file=.env.typegen --include-runtime=false --env-interface=WorkerBindings src/worker-configuration.d.ts` (hash: a4aedd3e9c55f6415076cdc86944ef0e)
interface __BaseEnv_WorkerBindings {
	DB: D1Database;
	AI: Ai;
	CF_VERSION_METADATA: WorkerVersionMetadata;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./index");
	}
	interface Env extends __BaseEnv_WorkerBindings {}
}
interface WorkerBindings extends __BaseEnv_WorkerBindings {}
