/* eslint-disable */
// Generated by Wrangler by running `wrangler types --env-file=.env.typegen --include-runtime=false --env-interface=WorkerBindings src/worker-configuration.d.ts` (hash: 74ab23474b68215c0e24e27918e8fb1e)
interface __BaseEnv_WorkerBindings {
	DB: D1Database;
	AI: Ai;
	CF_VERSION_METADATA: WorkerVersionMetadata;
	ADMIN_PASSWORD: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./index");
	}
	interface Env extends __BaseEnv_WorkerBindings {}
}
interface WorkerBindings extends __BaseEnv_WorkerBindings {}
